# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 16:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField()),
                ('active_begin', models.DateField(default=datetime.datetime(2016, 3, 14, 16, 7, 23, 389813))),
                ('active_end', models.DateField(default=datetime.datetime(2017, 3, 15, 16, 7, 23, 389838))),
                ('personal_ID', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('check_password', models.CharField(max_length=100)),
                ('entity_ID', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountsFtpaccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftp_username', models.CharField(max_length=100L, unique=True)),
                ('ftp_password', models.CharField(max_length=100L)),
                ('ftp_check_password', models.CharField(max_length=100L)),
                ('ftp_path', models.CharField(max_length=100L)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
            options={
                'db_table': 'accounts_ftpaccount',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Area')),
            ],
        ),
        migrations.CreateModel(
            name='DomainAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_active', models.BooleanField()),
                ('domain_active_begin', models.DateField(default=datetime.datetime(2016, 3, 14, 16, 7, 23, 394471))),
                ('domain_active_end', models.DateField(default=datetime.datetime(2017, 3, 15, 16, 7, 23, 394489))),
                ('domain_username', models.CharField(blank=True, max_length=100, unique=True)),
                ('domain_password', models.CharField(max_length=100)),
                ('check_password', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='DomainGroupType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JabberAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabber_active', models.BooleanField()),
                ('jabber_active_begin', models.DateField(default=datetime.datetime(2016, 3, 14, 16, 7, 23, 395253))),
                ('jabber_active_end', models.DateField(default=datetime.datetime(2017, 3, 15, 16, 7, 23, 395270))),
                ('jabber_username', models.CharField(blank=True, max_length=100, unique=True)),
                ('jabber_password', models.CharField(blank=True, max_length=100)),
                ('check_password', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='MailAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_active', models.BooleanField()),
                ('webmail_external_access', models.BooleanField()),
                ('mail_active_begin', models.DateField(default=datetime.datetime(2016, 3, 14, 16, 7, 23, 392786))),
                ('mail_active_end', models.DateField(default=datetime.datetime(2017, 3, 15, 16, 7, 23, 392803))),
                ('mail_username', models.EmailField(blank=True, max_length=100, unique=True)),
                ('mail_password', models.CharField(blank=True, max_length=100)),
                ('check_password', models.CharField(blank=True, max_length=100)),
                ('mail_quota', models.PositiveIntegerField(default=100)),
                ('mail_location', models.CharField(blank=True, max_length=100)),
                ('mail_dir', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='MailAccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_alias', models.EmailField(max_length=100)),
                ('mail_goto', models.EmailField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('mail_account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.MailAccountType')),
            ],
        ),
        migrations.CreateModel(
            name='ProxyAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_active', models.BooleanField()),
                ('proxy_active_begin', models.DateField(default=datetime.datetime(2016, 3, 14, 16, 7, 23, 391428))),
                ('proxy_active_end', models.DateField(default=datetime.datetime(2017, 3, 15, 16, 7, 23, 391446))),
                ('proxy_username', models.CharField(blank=True, max_length=100, unique=True)),
                ('proxy_password', models.CharField(blank=True, max_length=100)),
                ('check_password', models.CharField(blank=True, max_length=100)),
                ('proxy_quota', models.PositiveIntegerField(default=100)),
                ('proxy_quota_extra', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
        migrations.CreateModel(
            name='ProxyAccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProxyQuotaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='proxyaccount',
            name='proxy_account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ProxyAccountType'),
        ),
        migrations.AddField(
            model_name='proxyaccount',
            name='proxy_quota_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ProxyQuotaType'),
        ),
        migrations.AddField(
            model_name='mailaccount',
            name='mail_account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.MailAccountType'),
        ),
        migrations.AddField(
            model_name='domainaccount',
            name='domain_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.DomainGroupType'),
        ),
        migrations.AddField(
            model_name='account',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Department'),
        ),
    ]
