# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-12 21:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160314_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailaccount',
            name='webmail_external_access',
        ),
        migrations.AlterField(
            model_name='account',
            name='active_begin',
            field=models.DateField(default=datetime.datetime(2016, 12, 12, 21, 58, 10, 120687)),
        ),
        migrations.AlterField(
            model_name='account',
            name='active_end',
            field=models.DateField(default=datetime.datetime(2017, 12, 13, 21, 58, 10, 120730)),
        ),
        migrations.AlterField(
            model_name='domainaccount',
            name='domain_active_begin',
            field=models.DateField(default=datetime.datetime(2016, 12, 12, 21, 58, 10, 128542)),
        ),
        migrations.AlterField(
            model_name='domainaccount',
            name='domain_active_end',
            field=models.DateField(default=datetime.datetime(2017, 12, 13, 21, 58, 10, 128566)),
        ),
        migrations.AlterField(
            model_name='jabberaccount',
            name='jabber_active_begin',
            field=models.DateField(default=datetime.datetime(2016, 12, 12, 21, 58, 10, 129378)),
        ),
        migrations.AlterField(
            model_name='jabberaccount',
            name='jabber_active_end',
            field=models.DateField(default=datetime.datetime(2017, 12, 13, 21, 58, 10, 129415)),
        ),
        migrations.AlterField(
            model_name='mailaccount',
            name='mail_active_begin',
            field=models.DateField(default=datetime.datetime(2016, 12, 12, 21, 58, 10, 126628)),
        ),
        migrations.AlterField(
            model_name='mailaccount',
            name='mail_active_end',
            field=models.DateField(default=datetime.datetime(2017, 12, 13, 21, 58, 10, 126659)),
        ),
        migrations.AlterField(
            model_name='proxyaccount',
            name='proxy_active_begin',
            field=models.DateField(default=datetime.datetime(2016, 12, 12, 21, 58, 10, 122709)),
        ),
        migrations.AlterField(
            model_name='proxyaccount',
            name='proxy_active_end',
            field=models.DateField(default=datetime.datetime(2017, 12, 13, 21, 58, 10, 122749)),
        ),
    ]
