# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-12 22:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20161212_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='active_begin',
            field=models.DateField(default=datetime.datetime(2016, 12, 12, 22, 3, 26, 84384)),
        ),
        migrations.AlterField(
            model_name='account',
            name='active_end',
            field=models.DateField(default=datetime.datetime(2017, 12, 13, 22, 3, 26, 84495)),
        ),
        migrations.AlterField(
            model_name='domainaccount',
            name='domain_active_begin',
            field=models.DateField(default=datetime.datetime(2016, 12, 12, 22, 3, 26, 89839)),
        ),
        migrations.AlterField(
            model_name='domainaccount',
            name='domain_active_end',
            field=models.DateField(default=datetime.datetime(2017, 12, 13, 22, 3, 26, 89863)),
        ),
        migrations.AlterField(
            model_name='jabberaccount',
            name='jabber_active_begin',
            field=models.DateField(default=datetime.datetime(2016, 12, 12, 22, 3, 26, 90728)),
        ),
        migrations.AlterField(
            model_name='jabberaccount',
            name='jabber_active_end',
            field=models.DateField(default=datetime.datetime(2017, 12, 13, 22, 3, 26, 90751)),
        ),
        migrations.AlterField(
            model_name='mailaccount',
            name='mail_active_begin',
            field=models.DateField(default=datetime.datetime(2016, 12, 12, 22, 3, 26, 87728)),
        ),
        migrations.AlterField(
            model_name='mailaccount',
            name='mail_active_end',
            field=models.DateField(default=datetime.datetime(2017, 12, 13, 22, 3, 26, 87751)),
        ),
        migrations.AlterField(
            model_name='proxyaccount',
            name='proxy_active_begin',
            field=models.DateField(default=datetime.datetime(2016, 12, 12, 22, 3, 26, 86192)),
        ),
        migrations.AlterField(
            model_name='proxyaccount',
            name='proxy_active_end',
            field=models.DateField(default=datetime.datetime(2017, 12, 13, 22, 3, 26, 86217)),
        ),
    ]
